name: Bug Report Form
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - marcus-j-davies
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe observed behavior and expected behavior?
      placeholder: Tell us what you see!
      value: "A bug happened! Please describe the problem, drag pictures here if they are helpful to your story."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      placeholder: Reproduce!
      value: "Please list steps to reproduce. If the problem is hardware-specific, please list which devices are affected."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. 7.1.1
    validations:
      required: true
  - type: input
    id: nrversion
    attributes:
      label: Node-RED Version
      description: What version of Node-RED are you running?
      placeholder: ex. 3.0.0
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: What hardware are you seeing the problem on?
      multiple: true
      options:
        - Raspberry Pi
        - Other Linux
        - Mac OS
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Z-Wave-JS log as a text file
      description: Please upload your log file from zwave-js. Simply drag and drop a `.txt` file.
      render: shell
