name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: [enhancement]
assignees:
  - marcus-j-davies
body:
  - type: markdown
    attributes:
      value:
        We love new ideas!
  - type: textarea
    id: feature_description
    attributes:
      label: What is your idea?
      description: "Please describe your feature here:"
      placeholder: Tell us what you see!
      value: "Please describe your idea, drag screenshots or drawings here if they help your explanation. Please be as detailed as possible."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. 7.1.1
    validations:
      required: false
  - type: input
    id: nrversion
    attributes:
      label: Node-RED Version
      description: What version of Node-RED are you running?
      placeholder: ex. 3.0.0
    validations:
      required: false
  - type: dropdown
    id: hardware
    attributes:
      label: What hardware are you using?
      multiple: true
      options:
        - Raspberry Pi
        - Other Linux
        - Mac OS
        - Windows
        - Other
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Any code to add?
      description: "If you have any code (such as a JS function that does what you want or some JSON you would like to see output from the node), paste it here. This will be automatically formatted into code, so no need for backticks."
      render: shell
