name: Need Help
description: If you just need some help. don't hesitate to ask.
title: "[Help]: "
labels: [help-wanted]
assignees:
  - marcus-j-davies
  - crxporter
body:
  - type: markdown
    attributes:
      value:
        Our users are the best! We are happy to help any way we can.
  - type: textarea
    id: help-request
    attributes:
      label: How can we help?
      description: "Describe your question here"
      placeholder: Tell us what you see!
      value: "What's happening? Drag screenshots or drawings here if they help your explanation. Please be as detailed as possible."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. 7.1.1
    validations:
      required: false
  - type: input
    id: nrversion
    attributes:
      label: Node-RED Version
      description: What version of Node-RED are you running?
      placeholder: ex. 3.0.0
    validations:
      required: false
  - type: dropdown
    id: hardware
    attributes:
      label: What hardware are you using?
      multiple: true
      options:
        - Raspberry Pi
        - Other Linux
        - Mac OS
        - Windows
        - Other
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Any code to add?
      description: If you have any JS code or logs, paste it here. This will be automatically formatted into code, so no need for backticks.
      render: shell
