name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish-latest:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Publish
        run: |
          npm ci
          npm publish --provenance

  publish-beta:
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Publish
        run: |
          npm ci
          npm publish --tag beta --provenance