name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish-latest:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Publish
        run: |
          npm ci
          npm publish

  publish-beta:
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Publish
        run: |
          npm ci
          npm publish --tag beta